name: TRM Automation

on:
  schedule:
    - cron: '0 12 * * *'  # Ejecución diaria a las 7 AM hora Colombia (12:00 UTC)
  workflow_dispatch:       # Permite ejecución manual

env:
  PYTHON_VERSION: '3.10'

jobs:
  update-trm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests matplotlib seaborn
        
    - name: Create directories
      run: |
        mkdir -p data
        mkdir -p scripts
        
    - name: Verify files
      run: |
        echo "Estructura del repositorio:"
        ls -R
        
    - name: Run TRM script
      run: python scripts/trm_script.py
      
    - name: Commit changes
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/
        git commit -m "Update TRM data [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
