name: TRM Automation

on:
  schedule:
    - cron: '0 12 * * *'  # Ejecuci칩n diaria a las 7 AM hora Colombia (12:00 UTC)
  workflow_dispatch:       # Permite ejecuci칩n manual

jobs:
  update-trm:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Verificar estructura
      run: |
        echo "Contenido del repositorio:"
        ls -R
        
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests matplotlib seaborn
        
    - name: Crear directorios necesarios
      run: |
        mkdir -p data
        mkdir -p scripts
        
    - name: Ejecutar script TRM
      run: |
        python scripts/trm_script.py
        
    - name: Subir cambios
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/
        git commit -m "Actualizaci칩n autom치tica TRM [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
