name: TRM Colombia Daily

on:
  schedule:
    - cron: '0 14 * * *'  # 8 AM Colombia (UTC-5)
  workflow_dispatch:

jobs:
  extract-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install pandas requests

      - name: Run TRM Script
        run: python trm_script.py
        
      - name: Upload to Google Drive
        uses: r0adkll/upload-google-drive@v1.0.18
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          parent: "1gq_7fVr59aM3jk6MZNgSgLllv5LgENZq"  # Reemplazar con ID real
          file: "./trm_diaria.csv"
          name: "trm_diaria.csv"
