name: TRM Automation with History

on:
  schedule:
    - cron: '0 12 * * *'  # 7 AM Colombia (12 UTC)
  workflow_dispatch:

jobs:
  update-trm:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Añadir timeout
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests numpy
        echo "Dependencias instaladas"
        
    - name: Run TRM script with error handling
      run: |
        echo "Iniciando script..."
        python scripts/trm_script.py || echo "Script falló con código $?"
        echo "Verificando salida..."
        [ -f data/trm_actual.csv ] && echo "Archivo generado" || echo "No se generó archivo"
        
    - name: Commit changes
      if: success() || failure()  # Siempre ejecutar para diagnóstico
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git status
        git commit -m "Automatic TRM update attempt [skip ci]" || echo "Commit falló"
        git push || echo "Push falló"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
