name: TRM Automation with History
on:
  schedule:
    - cron: '0 8 * * *'  # Diario a las 8 AM UTC
  workflow_dispatch:

jobs:
  update-trm:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install seaborn pandas requests matplotlib
        
    - name: Create data directory
      run: |
        mkdir -p data
        mkdir -p images
        mkdir -p scripts
        
    - name: Run TRM script
      run: |
        python scripts/trm_script.py
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Actualización automática TRM [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

